title: 'Student Lives & Points of interest in Trentino'
description:
  The project 'Student Lives & Points of Interest in Trentino' was developed by Munkhdelger Bayanjargal and Nina Verbeeke for the 2023/2024 fall edition of the Knowledge Graph Engineering course at the University of Trento
remote_theme: jekyll/minima
